### ISSUE TITLE
Duration half seconds

### ISSUE THREAD

**Issue by lieselvink** [RockefellerArchiveCenter/scripts#23]
**Describe the bug**
The use of half seconds for a duration time isn't working.

**To reproduce**
1. Go to 'liesel_csv'
2. Enter in credentials, sequence number, start time and duration
3. When entering the duration in second, try entering 10.5. 
4. script then closes automatically

**Expected behavior**
I was under the impression that entering in the half second could be useful when creating clips. I would simply enter in".5" after the seconds and it would count another half a second for the clip.

**Error message or screenshots**
Unfortunately the script closes before I have time to take a screen shot.

**Impact on your work**
I can definitely work around this for now but would definitely be a great tool moving forward.

**Additional context**

**Comment by bonniegee** [comment]
I was able to reproduce this, and got this error message:

```
Traceback (most recent call last):
  File "extractClipGetInfo.py", line 109, in <module>
    length = getLength()
  File "extractClipGetInfo.py", line 28, in getLength
    seconds = int(input("Enter the seconds of the duration: "))
ValueError: invalid literal for int() with base 10: '3.5'
```
Need to turn the int() function on line 28 into float() but account for modulo in line 83.
