### ISSUE TITLE
Remove grep dependency so script can work on Windows

### ISSUE THREAD

**Issue by lieselvink** [RockefellerArchiveCenter/scripts#27]
**Describe the bug**
The script is closing after I enter in the sequence number.

**To reproduce**
1. Go to RAC_AV_CLIPS >work
2. Click on liesel_csv
3. Enter in ArchivesSpace credentials, the ref ID and sequence number. 
4. Python window closes.

**Expected behavior**
The python window would stay open.

**Error message or screenshots**
It closes too quickly for me to take a screen shot but I think a message appears.

**Impact on your work**
Doesn't allow me to create clip.

**Additional context**

**Comment by lieselvink** [comment]
Update: Tried using the python shell to see if the same problem occurred, which it did. After entering the sequence number, the below message occurs: 

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\lvink>cd /d S:\RAC_AV_CLIPS\Work

S:\RAC_AV_CLIPS\Work>liesel_csv.py
ArchivesSpace username: lvink
ArchivesSpace password:
Logging into ArchivesSpace...
New RefId? y/n/q: y
Enter the ArchivesSpace RefId: aad38c3e9b181cc61563b7a418614bcd
Number to start appending to file (e.g., 1): 1
'grep' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "S:\RAC_AV_CLIPS\Work\liesel_csv.py", line 117, in <module>
    startTime = getStartTime(refId)
  File "S:\RAC_AV_CLIPS\Work\liesel_csv.py", line 27, in getStartTime
    if checkDuration(refId):
  File "S:\RAC_AV_CLIPS\Work\liesel_csv.py", line 22, in checkDuration
    return int(os.popen(ffmpegCommand).read()) > 3600
ValueError: invalid literal for int() with base 10: ''

S:\RAC_AV_CLIPS\Work>

**Comment by bonniegee** [comment]
[This](https://github.com/RockefellerArchiveCenter/scripts/blob/master/extractClipGetInfo/extractClipGetInfo.py#L21 ) is the relevant line of code
