### ISSUE TITLE
Error in script

### ISSUE THREAD

**Issue by lieselvink** [RockefellerArchiveCenter/scripts#29]
**Describe the bug**
When trying to create a clip, the script acts as if it makes the clip but states in red, "3ffb22c2de6b6e692c35fb7c8b1903fc.mp4: Invalid argument". The clip appears to be created in the Clips folder but when I go to view it an error pops up that reads " Error -2002: a bad public movie atom was found in the movie (3ffb22c2de6b6e692c35fb7c8b1903fc.mp4).

**To reproduce**
1. Go to S:\RAC_AV_CLIPS\Work
2. Click on liesel_csv
3. Enter in information to make clip

**Expected behavior**
I would expect that the script would create the clip without seeing the line "3ffb22c2de6b6e692c35fb7c8b1903fc.mp4: Invalid argument" in red and the actual mp4 file would work.

**Error message or screenshots**

ArchivesSpace username: lvink
ArchivesSpace password:
Logging into ArchivesSpace...
New RefId? y/n/q: y
Enter the ArchivesSpace RefId: 3ffb22c2de6b6e692c35fb7c8b1903fc
Number to start appending to file (e.g., 1): 18
Video is more than 1 hour. Enter the hours of the start time: 1
Enter the minutes of the start time: 10
Enter the seconds of the start time: 49
Enter the minutes of the duration: 0
Enter the seconds of the duration: 46
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.1 (GCC) 20180722
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --e
nable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libblur
ay --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-
libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enab
le-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-li
bvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --en
able-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-
libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enabl
e-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enabl
e-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enab
le-dxva2 --enable-avisynth
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '3ffb22c2de6b6e692c35fb7c8b1903fc.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.4.101
  Duration: 01:27:46.62, start: 0.000000, bitrate: 3995 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 720x486 [
SAR 9:10 DAR 4:3], 3793 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)

    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp,
 193 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Output #0, mp4, to 'Clips/3ffb22c2de6b6e692c35fb7c8b1903fc_18.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.12.100
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 720x486 [
SAR 9:10 DAR 4:3], q=2-31, 3793 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (de
fault)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp,
 193 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
3ffb22c2de6b6e692c35fb7c8b1903fc.mp4: Invalid argument
frame=    0 fps=0.0 q=-1.0 Lsize=       0kB time=00:00:00.00 bitrate=N/A speed=
  0x
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing ove
rhead: unknown
Row added!
New RefId? y/n/q:

**Impact on your work**
This bug is not allowing me to create clips.

**Additional context**
Please let me know how I can further explain!

**Comment by bonniegee** [comment]
Is this happening only for 3ffb22c2de6b6e692c35fb7c8b1903fc.mp4, or for multiple videos?

**Comment by lieselvink** [comment]
Only for this specific one I think. I just made a clip previously to this instance and it worked fine.
