### ISSUE TITLE
Use ffprobe instead of ffmpeg to get duration

### ISSUE THREAD

**Issue by ghost** [RockefellerArchiveCenter/scripts#30]
Regarding `scripts/extractClipGetInfo/` and other scripts. The stderr output from `ffmpeg` is not meant to be machine parsed. Instead, you can use `ffprobe` to get a standard, simpler, and machine parseable output. Since it will provide just the duration (in seconds) you can also avoid the additional `grep`, `cut`, `sed`, and `awk` processes. Example:

    ffprobe -loglevel error -show_entries format=duration -of csv=p=0 input

See the [`ffprobe` documentation](https://ffmpeg.org/ffprobe.html) and [FFmpeg Wiki: FFprobe Tips](https://trac.ffmpeg.org/wiki/FFprobeTips#Duration) for more info.

**Comment by bonniegee** [comment]
Thank you! This would also fix #27

**Comment by ghost** [comment]
That was quick. However, you're requesting the stream duration instead of the format duration which can result in an output of `N/A` for some inputs such as Matroska (MKV). If that's a potential issue you can use the command in my first comment, or the "Format (container) duration" example in the FFwiki to get the format duration.
