### ISSUE TITLE
add_missing_dates.py accommodate records missing begin/end dates

### ISSUE THREAD

**Issue by a-berish** [RockefellerArchiveCenter/scripts#45]
# Describe the bug
Add_missing_dates.py fails when there is only a date expression (ao is missing begin/end dates) on any given level.

# To reproduce
Run on development server:
1. run `python3 add_missing_dates.py -l series -r 12753`
2. see error: `Cannot calculate dates for /repositories/2/archival_objects/1081918`
3. see [archival object](http://192.168.50.7:8080/resources/12753/edit#tree::archival_object_1081918)
4. see an additional error (from running script without arguments): `Cannot calculate dates for /repositories/2/archival_objects/2650`
5. see [archival object](http://192.168.50.7:8080/resources/17#tree::archival_object_2650) associated with the error in step 4

# Expected behavior
Expected script to use date expression when begin/end dates are missing.

# Impact on your work
Many finding aids have either both date expressions + begin/end dates, or ONLY date expressions. The script will likely fail on those missing begin/end dates, leaving many records with missing dates.

**Comment by helrond** [comment]
I think this is likely something we want to separate out to a different script and project. Parsing date expressions into structured date formats is non-trivial, and will probably require some trial and error. 

I'm wondering about order of operations - does it make sense to try and run the date calculation script _before_ trying to parse date expressions, or should we prioritize date expression parsing and do the date calculation later?

**Comment by helrond** [comment]
Closing as this is being handled differently and is out-of-scope for this repository.
