### ISSUE TITLE
add_missing_dates.py fix incorrectly formatted dates

### ISSUE THREAD

**Issue by a-berish** [RockefellerArchiveCenter/scripts#46]
# Describe the bug
Script fails when there is an incorrectly formatted date in the begin/end date field.

# To reproduce
Run on development server:
1. `python3 add_missing_date.py -l series -a -r 11345`
2. see error: `{error: 'Not a date: 1993-03-1'}`
3. see [archival object](http://192.168.50.7:8080/resources/11345#tree::resource_11345) for error

# Expected behavior
None - did not expect incorrectly formatted dates. We might have to manually address these scenarios in Archivesspace.

**Comment by helrond** [comment]
I think we'll likely need to find a strategy to address these scenarios more manually. Unfortunately the date calculator doesn't provide much information about errors (for example where the unexpected value was found) so there might be some intermediary steps we need to take to find the right component and date object.

**Comment by helrond** [comment]
Closing as this is being handled differently and is out-of-scope for this repository.
