### ISSUE TITLE
add_missing_dates.py add functionality to run on published resources only

### ISSUE THREAD

**Issue by a-berish** [RockefellerArchiveCenter/scripts#47]
# Describe the bug
Script fails when there are two dates on any given level. For example, many unpublished resources have two dates: undated, and a _real_ inclusive date. 

# To reproduce
Run on development server:
1. 'python3 add_missing_dates.py -r 3'
2. see error: `Cannot calculate dates for repositories/2/archival_objects/213`
3. see [archival object](http://192.168.50.7:8080/resources/3#tree::archival_object_213)
4. another scenario where there are two dates: [archival object](http://192.168.50.7:8080/resources/8#tree::archival_object_366)

# Expected behavior
Expected script to use the inclusive date set and bypass the undated entry. Most of these cases exist only in unpublished records, so it may make more sense to be able to run the script on published resources only to avoid these errors. 

# Impact on your work
Since the script runs on everything, it takes longer to complete if you were to run it over the entire AS repository. It also throws errors when it encounters bad data on unpublished resources, making it difficult to find instances where the script might run into _actual_ errors with published data.

**Comment by a-berish** [comment]
The script also outputs confusing error messages when it attempts to record dates for archival objects that have a numerical date span in the "date expression" field.

To reproduce:
Run on development server:
1. `python3 add_missing_dates.py -a -r 11682`
2. see output/error: 
Dates update for /repositories/2/resources/11682
Cannot calculate dates for /repositories/2/resource/11682
3. See [archival object](http://192.168.50.7:8080/resources/11682#tree::resource_11682) in AS
4. Excerpt from date field: 
> Expression: 1936-01-01-2006-12-31
Begin: 1936-01-01
End: 2006-12-31

Other comments:
The example above is an unpublished resource. These cases only seem to be present for unpublished data.

**Comment by helrond** [comment]
Implementing logic to only calculate dates in unpublished resources might actually be pretty complex, since the basic `for` loop is looking at archival_objects, so we'd have to get the resource for each of those and then check see if it is unpublished. My sense is that this would make performance even worse.

I believe the second scenario posted here is a bug in the script which I'll look into. I'm not sure what's causing the first scenario, but I'll look at it a bit more.

**Comment by helrond** [comment]
Closing as this is being handled differently and is out-of-scope for this repository.
