### ISSUE TITLE
add_missing_dates.py fails when there are inclusive dates that should be single dates

### ISSUE THREAD

**Issue by a-berish** [RockefellerArchiveCenter/scripts#48]
# Describe the bug
Scripts fails to update dates when there are inclusive dates that should be single dates.

# To reproduce
Run on development server:
1. `python3 add_missing_dates.py -a`
2. see error: Cannot calculate dates for /repositories/2/archival_objects/367
3. see [archival object](http://192.168.50.7:8080/resources/8#tree::archival_object_367`)
4. this series (actually unidentified level) has a date expression + begin/end dates that really should be a single date: 1986. See excerpt from date field:
> Expression: 1986-1986
Begin: 1986-01-01
End: 1986-12-31
Type: Inclusive Dates

Additional example of this error:
[archival object](http://192.168.50.7:8080/resources/2#tree::archival_object_161)

# Expected behavior
Did not expect dates to be recorded this way. Perhaps the script can change date type to single when both dates in an inclusive date are the same?

# Additional context
There are few examples of this, not sure if these dates are a result of importing data into AS? Were months/days required in the begin/end date fields at one point?

**Comment by helrond** [comment]
Closing as this is being handled differently and is out-of-scope for this repository.
