### ISSUE TITLE
Add support for multiple resource ids to get_labels.py

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/scripts#52]
# Is your feature request related to a problem? Please describe.
It's frustrating to run the script multiple times.

# Describe the solution you'd like
I'd like to put all of the resource ids that I want to the script to run against a list of resource ids that I enter in the command line while running it. The script could be run automatically against each one once these are entered. I think argparse might be able to handle lists.

# Describe alternatives you've considered
No other alternatives right now.

# Additional context
Something the D-Team thought might improve the workflow.

**Comment by helrond** [comment]
For our future selves: [here](https://stackoverflow.com/questions/15753701/how-can-i-pass-a-list-as-a-command-line-argument-with-argparse) is a reference for how to do this.

**Comment by helrond** [comment]
This issue is pretty stale, and no strong user need has emerged to validate this use case, so closing this issue.
